"""Minimal local stub for the pypdfium2 v5 surface osr-forge uses.

pypdfium2 ships no py.typed marker and typeshed has no stubs for it; this file
covers exactly the API `osrforge.preprocess` consumes so pyright strict can
check the call sites.
"""

from pathlib import Path

from PIL.Image import Image

class PdfiumError(RuntimeError): ...

class PdfBitmap:
    def to_pil(self) -> Image: ...

class PdfTextPage:
    def get_text_bounded(
        self,
        left: float | None = None,
        bottom: float | None = None,
        right: float | None = None,
        top: float | None = None,
        errors: str = "ignore",
    ) -> str: ...
    def close(self) -> None: ...

class PdfPage:
    def render(self, scale: float = 1, rotation: int = 0) -> PdfBitmap: ...
    def get_textpage(self) -> PdfTextPage: ...
    def get_size(self) -> tuple[float, float]: ...
    def close(self) -> None: ...

class PdfDocument:
    def __init__(self, input_data: str | Path | bytes, password: str | None = None) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> PdfPage: ...
    def close(self) -> None: ...
